name: package shoecomp into FIJI
on:
  workflow_dispatch:
  release:
    types: [created]
  create:
    tags:
      - v.*

jobs:
  build_jar:
    name: package shoecomp into FIJI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fiji_target: [linux64, win64, macosx]
    steps:
      - name: checkout repo
        id: checkout_repo
        uses: actions/checkout@v4
      - name: setup JDK
        uses: actions/setup-java@v4
        id: jdk_setup
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: build JAR
        run: bash ./.github/scripts/build-jar.sh
      - name: create plugins folder
        run: mkdir -p plugins && ls -alh
      - name: copy plugins
        run: bash ./.github/scripts/collect-jars.sh
      - name: package for {{ fiji_target }}
        run: bash ./.github/scripts/pkg-{{ fiji_target }}.sh
      - name: upload release ZIP
        id: upload_zip
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NUMBER: ${{ env.VERSION_NUMBER }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fiji-{{ fiji_target }}.zip
          overwrite: true
          asset_name: shoecomp-fiji-{{ fiji_target }}.zip
