name: shoecomp JAR release
on:
  workflow_dispatch:
  release:
    types: [created]
  create:
    tags:
      - v.*

jobs:
  build_jar:
    name: build shoecomp JAR
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        id: checkout_repo
        uses: actions/checkout@v4
      - name: setup JDK
        uses: actions/setup-java@v4
        id: jdk_setup
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: build JAR
        run: bash ./.github/scripts/build-jar.sh
      - name: rename JAR
        run: cp target/shoecomp-1.0-SNAPSHOT-shaded.jar shoecomp-1.0.jar
      - name: upload release assets
        id: upload_assets
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          prerelease: true
          files: shoecomp-1.0.jar
